//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace AdvancedSqlServerDependencies.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class UserSettings : ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Value in seconds representing how much time will application wait for command to execute
        /// </summary>
        [UserScopedSetting()]
        [SettingsDescription("Value in seconds representing how much time will application wait for command to " +
            "execute")]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int CommandTimeout {
            get {
                return ((int)(this["CommandTimeout"]));
            }
            set {
                this["CommandTimeout"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool UseAlternatingBackColors {
            get {
                return ((bool)(this["UseAlternatingBackColors"]));
            }
            set {
                this["UseAlternatingBackColors"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Info")]
        public Color AlternateRowBackColor {
            get {
                return ((Color)(this["AlternateRowBackColor"]));
            }
            set {
                this["AlternateRowBackColor"] = value;
            }
        }
    }
}
